export const spoilSrc: Record<string, string> = {
  butterfly: './spoil/butterfly.svg',
  frog: './spoil/frog.svg',
  mouse: './spoil/mouse.svg',
  bird: './spoil/bird.svg',
  star: './icons/star.svg',
}

export const iconSrc: Record<string, string> = {
  cat: './icons/favicon.svg',
  check: './icons/check.svg',
  close: './icons/close.svg',
  restart: './icons/restart.svg',
  settings: './icons/settings.svg',
  menu: './icons/menu.svg',
  play: './icons/play.svg',
  start: './icons/play-circle.svg',
  star: './icons/star.svg',
  about: './icons/about.svg',
  tooltip: './icons/tooltip.svg',
  fullscreen: './icons/fullscreen.svg',
  fullscreenExit: './icons/fullscreen-exit.svg',
  pause: './icons/pause.svg',
  soundOn: './icons/sound-on.svg',
  soundOff: './icons/sound-off.svg',
  sound: './icons/sound.svg',
  music: './icons/music.svg',
  paw: './icons/paw.svg',
  fps: './icons/fps.svg',
  globe: './icons/globe.svg',
  gamepad: './icons/gamepad.svg',
  pointer: './icons/mouse.svg',
  keyboard: './icons/keyboard.svg',
  upgrade: './icons/upgrade.svg',
  eye: './icons/eye.svg',
  claws: './icons/claws.svg',
  jump: './icons/jump.svg',
  speed: './icons/speed.svg',
  en: './flag/en.svg',
  ru: './flag/ru.svg',
  de: './flag/de.svg',
  tr: './flag/tr.svg',
  fr: './flag/fr.svg',
}
