export const spoilSrc: Record<string, string> = {
  butterfly: './spoil/butterfly.svg',
  grasshopper: './spoil/frog.svg',
  frog: './spoil/frog.svg',
  mouse: './spoil/mouse.svg',
  bird: './spoil/bird.svg',
}

export const iconSrc: Record<string, string> = {
  check: './icons/check.svg',
  close: './icons/close.svg',
  resume: './icons/play.svg',
  restart: './icons/restart.svg',
  settings: './icons/settings.svg',
  menu: './icons/menu.svg',
  play: './icons/play.svg',
  about: './icons/about.svg',
  fullscreen: './icons/fullscreen.svg',
  fullscreenExit: './icons/fullscreen-exit.svg',
  pause: './icons/pause.svg',
  soundOn: './icons/sound-on.svg',
  soundOff: './icons/sound-off.svg',
  sound: './icons/sound.svg',
  music: './icons/music.svg',
  paw: './icons/paw.svg',
  fps: './icons/fps.svg',
  globe: './icons/globe.svg',
  gamepad: './icons/gamepad.svg',
  en: './flag/en.svg',
  ru: './flag/ru.svg',
  de: './flag/de.svg',
  tr: './flag/tr.svg',
  fr: './flag/fr.svg',
}
